### PR TITLE
Better error handling of conceptschemes that fail to load. Refs #101

### PR DESCRIPTION
**Pull request by koenedaele**
In case the CS fails to load, fall back on the CS uri as a label since that one's always present.

@Wim-De-Clercq Could you review and provide a unit tests that tests the error handling?

### CODE REVIEW

**Comment by Wim-De-Clercq** [comment]
Remark:
The `ProviderUnavailableException` in the case of the ticket happens because `provider.concept_scheme` will do a request which fails.

The fallback `get_vocabulary_uri()` may also try doing `provider.concept_scheme` in case the metadata has no `uri`.
```py
    def get_vocabulary_uri(self):
        try:
            return self.metadata['uri']
        except KeyError:
            return self.concept_scheme.uri
```

In the known case of the Gettyproviders this can never happen. `metadata` is guaranteed to have an URI. But **in theory** it could still fail.


I noticed in the test because I mock a DictionaryProvider to raise a `ProviderUnavailableException` upon retrieving the concept_scheme. As happens with the GettyProviders.
But then I saw another error being raised during `get_vocabulary_uri`. That's why the test has an extra mock to make `get_vocabulary_uri` return a value.

**Review by koenedaele — COMMENTED** [review]
I just realised it doesn't make sense to fall back on an empty label if there's no label but to fall back on the URI if the provider is down. I'm fine with always falling back to None.

**Comment by koenedaele** [comment]
> Remark: The `ProviderUnavailableException` in the case of the ticket happens because `provider.concept_scheme` will do a request which fails.
> 
> The fallback `get_vocabulary_uri()` may also try doing `provider.concept_scheme` in case the metadata has no `uri`.
> 
> ```python
>     def get_vocabulary_uri(self):
>         try:
>             return self.metadata['uri']
>         except KeyError:
>             return self.concept_scheme.uri
> ```
> 
> In the known case of the Gettyproviders this can never happen. `metadata` is guaranteed to have an URI. But **in theory** it could still fail with a provider who has no uri in the metadata AND raises a `ProviderUnavailableException` for getting the label.
> 
> I noticed this in the test because I mock a DictionaryProvider to raise a `ProviderUnavailableException` upon retrieving the concept_scheme. As happens with the GettyProviders. But then I saw another error being raised during `get_vocabulary_uri`. That's why the test has an extra mock to make `get_vocabulary_uri` return a value.

True. The default implementation works well for the default in-memory skosproviders where the concept_scheme is created with the entire vocabulary. For more complicated providers such as the Getty one, it's up to the implementor to make the skosprovider as robust as possible. The vocabulary URI get special attention because it's needed by the registry when registering a provider (together with the ID), the rest of the conceptscheme is not needed to instantiate the provider. So the get_vocabulary_uri method makes it possible for an implementor to avoid a call to a service just to get a URI since quite often this would prevent Atramhasis from loading the registry and starting the application.

**Comment by Wim-De-Clercq** [comment]
> I just realised it doesn't make sense to fall back on an empty label if there's no label but to fall back on the URI if the provider is down. I'm fine with always falling back to None.

Makes sense indeed.

**Pull request merged**
